import { accountFromRequest } from "@/lib/portal/auth";
import { ageFromDateOfBirth, assertCsrf, cleanText, POLICY_VERSION } from "@/lib/portal/security";
import { audit, clientIp, mutatePortalDatabase, newId } from "@/lib/portal/store";
import { apiError, emailPattern, phonePattern, validationResponse } from "@/lib/portal/validation";

export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) {
  try { assertCsrf(request); } catch { return apiError("Your secure form session expired. Refresh and try again.", 403, "CSRF_FAILED"); }
  const account = await accountFromRequest(request, { verified: true }); if (!account) return apiError("Please log in again.", 401, "AUTH_REQUIRED");
  const { id } = await params; const payload = await request.json().catch(() => ({})) as Record<string, unknown>;
  const fullName=cleanText(payload.fullName,160), dateOfBirth=cleanText(payload.dateOfBirth,10), gender=cleanText(payload.gender,40), phone=cleanText(payload.phone,40), email=cleanText(payload.email,254).toLowerCase(), previousExperience=cleanText(payload.previousExperience,1200), medicalChoice=cleanText(payload.medicalChoice,3), medicalDetails=cleanText(payload.medicalDetails,1600), electronicSignature=cleanText(payload.electronicSignature,160); const age=ageFromDateOfBirth(dateOfBirth); const errors:Record<string,string>={};
  if(!fullName)errors.fullName="Please enter the student’s full name.";if(age===null)errors.dateOfBirth="Please enter a valid date of birth.";else if(age<5)errors.dateOfBirth="Students must be at least five years old.";if(!["Female","Male","Non-binary","Prefer not to say"].includes(gender))errors.gender="Please select a gender option.";if(phone&&!phonePattern.test(phone))errors.phone="Please enter a valid phone number.";if(email&&!emailPattern.test(email))errors.email="Please enter a valid email address.";if(!previousExperience)errors.previousExperience="Please describe previous experience, or enter “None”.";if(!["Yes","No"].includes(medicalChoice))errors.medicalChoice="Please select Yes or No.";if(medicalChoice==="Yes"&&!medicalDetails)errors.medicalDetails="Please provide the relevant details.";if(!payload.acceptsWaiver)errors.acceptsWaiver="You must accept the Liability Waiver.";if(!electronicSignature)errors.electronicSignature="Please enter the required electronic signature.";if(Object.keys(errors).length)return validationResponse(errors);
  const updated=await mutatePortalDatabase((database)=>{const student=database.students.find((item)=>item.id===id&&item.accountId===account.id);if(!student)return false;Object.assign(student,{fullName,dateOfBirth,gender,phone,email,previousExperience,hasMedicalConditions:medicalChoice==="Yes",medicalDetails:medicalChoice==="Yes"?medicalDetails:"",guardianName:age!==null&&age<18?`${account.firstName} ${account.lastName}`:"",guardianPhone:age!==null&&age<18?account.phone:"",guardianEmail:age!==null&&age<18?account.email:"",photoVideoPermission:Boolean(payload.photoVideoPermission),electronicSignature,updatedAt:new Date().toISOString()});database.waiver_acceptances.push({id:newId("consent"),accountId:account.id,studentId:id,consentType:"liability-waiver",accepted:true,version:POLICY_VERSION,acceptedAt:new Date().toISOString(),ipAddress:clientIp(request)});audit(database,request,account.id,"student.updated","student",id);return true;});
  if(!updated)return apiError("The student record was not found.",404,"NOT_FOUND");return Response.json({success:true,nextUrl:"/account/dashboard"});
}
