"use client";
import { useState } from "react";
import { portalFetch } from "@/lib/client/portal-fetch";

const input = "mt-2 w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-white outline-none focus:border-red-400";
export function ForgotPasswordForm() {
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const email=String(new FormData(event.currentTarget).get("email")||"");const response=await portalFetch("/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const data=await response.json() as {message?:string};setMessage(data.message||"The request could not be completed.");setBusy(false);}
  return <form onSubmit={submit}><label className="text-sm font-semibold text-stone-200">Account email<input className={input} name="email" type="email" autoComplete="email" required /></label>{message?<p role="status" className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-stone-200">{message}</p>:null}<button disabled={busy} className="mt-6 min-h-12 w-full rounded-md bg-red-600 px-5 text-sm font-black uppercase tracking-[0.12em] text-white disabled:opacity-60">{busy?"Sending…":"Send Reset Link"}</button></form>;
}
export function ResetPasswordForm({token}:{token:string}) {
  const [show,setShow]=useState(false);const [message,setMessage]=useState("");const [errors,setErrors]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setErrors({});const form=new FormData(event.currentTarget);const response=await portalFetch("/api/auth/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password:form.get("password"),confirmPassword:form.get("confirmPassword")})});const data=await response.json() as {message?:string;fieldErrors?:Record<string,string>;nextUrl?:string};if(!response.ok){setErrors(data.fieldErrors||{});setMessage(data.message||"Password reset failed.");}else{setMessage(data.message||"Password changed.");setTimeout(()=>window.location.assign(data.nextUrl||"/account"),1000);}setBusy(false);}
  return <form onSubmit={submit}><label className="text-sm font-semibold text-stone-200">New password<input className={`${input} ${errors.password?"border-red-400":""}`} name="password" type={show?"text":"password"} autoComplete="new-password" />{errors.password?<p className="mt-2 text-sm text-red-300">{errors.password}</p>:null}</label><label className="mt-5 block text-sm font-semibold text-stone-200">Confirm password<input className={`${input} ${errors.confirmPassword?"border-red-400":""}`} name="confirmPassword" type={show?"text":"password"} autoComplete="new-password" />{errors.confirmPassword?<p className="mt-2 text-sm text-red-300">{errors.confirmPassword}</p>:null}</label><label className="mt-4 flex gap-2 text-sm text-stone-300"><input type="checkbox" checked={show} onChange={(event)=>setShow(event.target.checked)} /> Show passwords</label><p className="mt-4 text-xs leading-6 text-stone-400">Use at least 12 characters with uppercase, lowercase, number, and special character.</p>{message?<p role="status" className="mt-5 rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-stone-200">{message}</p>:null}<button disabled={busy} className="mt-6 min-h-12 w-full rounded-md bg-red-600 px-5 text-sm font-black uppercase tracking-[0.12em] text-white disabled:opacity-60">{busy?"Updating…":"Change Password"}</button></form>;
}
