import Link from "next/link";
import { AdminRegistrationActions } from "@/components/AdminRegistrationActions";
import { requireAccount } from "@/lib/portal/auth";
import { money } from "@/lib/portal/security";
import { readPortalDatabase } from "@/lib/portal/store";

export const dynamic = "force-dynamic";
const headings = ["Submitted", "Reference", "Account", "Participant", "Training", "Tuition", "Registration", "Payment", "Transaction / Receipt", "Actions"];

export default async function Page() {
  await requireAccount({ verified: true, admin: true });
  const database = await readPortalDatabase(), enrollments = [...database.enrollments].sort((a, b) => b.createdAt.localeCompare(a.createdAt)), registrations = [...database.registrations].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
  return <main className="min-h-screen bg-stone-950 px-4 py-20 text-white sm:px-6"><div className="mx-auto max-w-7xl">
    <div className="mb-8 rounded-3xl border border-white/10 bg-black/60 p-8"><p className="text-xs font-black uppercase tracking-[0.28em] text-red-300">Role-protected administration</p><h1 className="mt-3 text-3xl font-black uppercase sm:text-4xl">Registration & Payment Review</h1><p className="mt-3 text-stone-300">Only verified administrator accounts can confirm payment and activate registrations.</p><div className="mt-5 flex flex-wrap gap-4 text-sm"><Link className="text-red-300" href="/account/dashboard">← Family Dashboard</Link><Link className="text-red-300" href="/admin/knowledge-center">Manage Knowledge Center →</Link></div></div>
    <h2 className="mb-4 text-2xl font-black">Simplified Registrations</h2><div className="mb-10 overflow-x-auto rounded-2xl border border-white/10 bg-black/50"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-white/5 text-stone-300"><tr>{headings.map((heading) => <th className="px-4 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-white/10">{registrations.map((entry) => { const payment = database.payments.filter((item) => item.registrationId === entry.id).sort((a, b) => b.submittedAt.localeCompare(a.submittedAt))[0]; return <tr className="align-top" key={entry.id}><td className="whitespace-nowrap px-4 py-4">{new Date(entry.createdAt).toLocaleString("en-CA")}</td><td className="px-4 py-4 font-bold text-red-200">{entry.registrationReference}</td><td className="px-4 py-4">Direct registration<br /><span className="text-stone-400">{entry.email}</span></td><td className="px-4 py-4">{entry.fullName}</td><td className="px-4 py-4">SHOTOKAN Karate</td><td className="px-4 py-4">{money(entry.tuitionCents)}</td><td className="px-4 py-4">{entry.registrationStatus}</td><td className="px-4 py-4">{entry.paymentStatus}</td><td className="px-4 py-4">{payment?.transactionReference || "—"}{payment?.receiptId && <><br /><a className="text-red-300" href={`/api/receipts/${payment.receiptId}`} target="_blank">Private receipt</a></>}</td><td className="px-4 py-4"><AdminRegistrationActions id={entry.id} paymentStatus={entry.paymentStatus} recordType="direct-registration" /></td></tr>; })}</tbody></table>{!registrations.length && <p className="p-8 text-stone-400">No simplified registrations have been received.</p>}</div>
    <h2 className="mb-4 text-2xl font-black">Family Account Enrollments</h2><div className="overflow-x-auto rounded-2xl border border-white/10 bg-black/50"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-white/5 text-stone-300"><tr>{headings.map((heading) => <th className="px-4 py-3" key={heading}>{heading}</th>)}</tr></thead><tbody className="divide-y divide-white/10">{enrollments.map((entry) => { const account = database.accounts.find((item) => item.id === entry.accountId), student = database.students.find((item) => item.id === entry.studentId), karateClass = database.classes.find((item) => item.id === entry.classId), payment = database.payments.filter((item) => item.enrollmentId === entry.id).sort((a, b) => b.submittedAt.localeCompare(a.submittedAt))[0]; return <tr className="align-top" key={entry.id}><td className="whitespace-nowrap px-4 py-4">{new Date(entry.createdAt).toLocaleString("en-CA")}</td><td className="px-4 py-4 font-bold text-red-200">{entry.registrationReference}</td><td className="px-4 py-4">{account?.firstName} {account?.lastName}<br /><span className="text-stone-400">{account?.email}</span></td><td className="px-4 py-4">{student?.fullName}</td><td className="px-4 py-4">{karateClass?.name}</td><td className="px-4 py-4">{money(entry.tuitionCents)}</td><td className="px-4 py-4">{entry.enrollmentStatus}</td><td className="px-4 py-4">{entry.paymentStatus}</td><td className="px-4 py-4">{payment?.transactionReference || "—"}{payment?.receiptId && <><br /><a className="text-red-300" href={`/api/receipts/${payment.receiptId}`} target="_blank">Private receipt</a></>}</td><td className="px-4 py-4"><AdminRegistrationActions id={entry.id} paymentStatus={entry.paymentStatus} /></td></tr>; })}</tbody></table>{!enrollments.length && <p className="p-8 text-stone-400">No family-account enrollments have been received.</p>}</div>
  </div></main>;
}
