import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ButtonLink } from "@/components/ButtonLink";
import { Footer } from "@/components/Footer";
import { KnowledgeResourceLibrary } from "@/components/KnowledgeResourceLibrary";
import { Navbar } from "@/components/Navbar";
import { getPublishedKnowledgeContent } from "@/lib/knowledge/store";

export const metadata: Metadata = {
  title: { absolute: "Karate Refereeing Education and Competition Rules | Regina, Canada" },
  description: "Learn about karate refereeing, Kata judging, Kumite rules, Para Karate, scoring, penalties, signals, and professional competition procedures.",
  alternates: { canonical: "/karate-refereeing" },
  keywords: ["karate referee", "karate refereeing", "karate judging", "WKF karate rules", "Kata judging rules", "Kumite referee rules", "Kumite scoring", "Para Karate rules", "karate officiating Canada", "karate referee Saskatchewan", "karate referee Regina"],
  openGraph: { title: "Karate Refereeing Education and Competition Rules", description: "Rules, judging procedures, competition standards, and verified educational resources for modern karate.", url: "/karate-refereeing", images: [{ url: "/images/coach-reza-portrait.jpg", width: 1200, height: 876, alt: "Coach Reza Abbasi, official karate referee and coach in Saskatchewan" }] },
};

const modules = [
  ["01", "Introduction to Karate Refereeing", ["Role of the referee", "Role of the judges", "Responsibilities of officials", "Competition-area organization", "Professional conduct", "Communication between officials", "Referee positioning and movement"]],
  ["02", "Kata Judging", ["Kata competition structure", "Evaluation process", "Technical performance", "Athletic performance", "Accuracy and control", "Balance, power, rhythm, and timing", "Deductions", "Disqualification", "Tie-breaking procedures", "Common judging mistakes"]],
  ["03", "Kumite Refereeing", ["Kumite competition structure", "Point-scoring criteria", "Yuko, Waza-ari, and Ippon", "Match duration", "Referee positioning", "Judge signals", "Warnings and penalties", "Prohibited behaviour", "Injuries and safety procedures", "Senshu", "Video Review", "Match interruption and continuation", "Disqualification procedures", "Winner determination"]],
  ["04", "Para Karate Officiating", ["Para Karate overview", "Competition categories", "Classification principles", "Adapted judging considerations", "Safety responsibilities", "Competition procedures", "Accessibility and respectful officiating"]],
  ["05", "Referee Signals and Terminology", ["Official commands", "Hand signals", "Flag signals", "Scoring terminology", "Penalty terminology", "Starting, stopping, and ending matches"]],
  ["06", "Practical Referee Development", ["Studying competition rules", "Shadow judging", "Tournament experience", "Decision-making exercises", "Positioning practice", "Video analysis", "Continuing education", "Professional conduct and impartiality"]],
] as const;

const faqs = ["What is the role of a karate referee?", "What is the difference between a referee and a judge?", "How is Kata evaluated?", "How are Kumite points awarded?", "What actions can result in a warning or penalty?", "What is Senshu?", "How does Video Review work?", "What happens when an athlete is injured?", "What is Para Karate?", "How can someone begin learning karate refereeing?", "Why do athletes and coaches need to understand competition rules?"];

export default async function KarateRefereeingPage() {
  const { resources, articles } = await getPublishedKnowledgeContent();
  const structuredData = {
    "@context": "https://schema.org",
    "@graph": [
      { "@type": "Article", headline: "Karate Refereeing Education", description: metadata.description, author: { "@type": "Person", name: "Coach Reza Abbasi" }, publisher: { "@type": "Organization", name: "SHOTOKAN Karate Regina" }, mainEntityOfPage: "https://shotokan-karate-regina.vercel.app/karate-refereeing" },
      { "@type": "BreadcrumbList", itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: "https://shotokan-karate-regina.vercel.app/" },
        { "@type": "ListItem", position: 2, name: "Knowledge Center", item: "https://shotokan-karate-regina.vercel.app/karate-knowledge-center" },
        { "@type": "ListItem", position: 3, name: "Karate Refereeing Education", item: "https://shotokan-karate-regina.vercel.app/karate-refereeing" },
      ] },
    ],
  };

  return <><Navbar /><main className="overflow-hidden bg-black pt-20"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <section className="relative min-h-[38rem] border-b border-white/10 bg-stone-950"><div className="absolute inset-0 opacity-60 [background-image:linear-gradient(90deg,transparent_49.8%,rgba(255,255,255,0.1)_50%,transparent_50.2%),linear-gradient(0deg,transparent_49.8%,rgba(215,25,32,0.22)_50%,transparent_50.2%),repeating-linear-gradient(90deg,rgba(255,255,255,0.025)_0,rgba(255,255,255,0.025)_1px,transparent_1px,transparent_6rem)]" /><div className="absolute inset-0 bg-gradient-to-r from-black via-black/85 to-black/35" /><div className="section-shell relative flex min-h-[38rem] flex-col justify-center py-16"><nav aria-label="Breadcrumb" className="mb-14 text-sm text-stone-400"><ol className="flex flex-wrap gap-2"><li><Link href="/">Home</Link></li><li aria-hidden="true">/</li><li><Link href="/karate-knowledge-center">Knowledge Center</Link></li><li aria-hidden="true">/</li><li aria-current="page" className="text-white">Refereeing</li></ol></nav><div className="max-w-4xl"><p className="text-xs font-black uppercase tracking-[0.28em] text-red-300">Karate Refereeing Education</p><h1 className="hero-title mt-4 text-balance text-4xl font-bold leading-tight text-white sm:text-6xl lg:text-7xl">Professional Karate Refereeing Education</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-stone-200">Learn the rules, decisions, scoring systems, signals, and competition procedures used in professional Kata, Kumite, and Para Karate events.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/karate-refereeing/resources">Open PDF Library</ButtonLink><ButtonLink href="#curriculum" variant="secondary">View Education Modules</ButtonLink></div><p className="mt-8 text-sm text-stone-500">A verified competition photograph of Coach Reza Abbasi officiating in Canada will replace this neutral competition-area treatment when supplied.</p></div></div></section>

    <section className="bg-stone-950 py-20 sm:py-24"><div className="section-shell"><div className="grid items-center gap-10 lg:grid-cols-[0.75fr_1.25fr]"><div className="relative mx-auto aspect-[37/27] w-full max-w-xl overflow-hidden rounded-2xl border border-red-400/25"><Image src="/images/coach-reza-portrait.jpg" alt="Coach Reza Abbasi, official karate referee and Saskatchewan provincial Kumite coach" fill className="object-cover" sizes="(min-width:1024px) 40vw, 100vw" /></div><div><p className="text-xs font-black uppercase tracking-[0.26em] text-red-300">Instructor and author</p><h2 className="hero-title mt-3 text-4xl font-bold text-white sm:text-5xl">Coach Reza Abbasi</h2><p className="mt-5 text-lg leading-8 text-stone-300">Coach Reza Abbasi shares professional educational materials to help athletes, coaches, parents, officials, and developing referees better understand karate competition rules and officiating procedures.</p><ul className="mt-6 grid gap-3 sm:grid-cols-2">{["Official Karate Federation Referee", "Official Kumite Coach — Saskatchewan Provincial Karate Team", "5th Dan Shotokan Karate Instructor", "Certified Level 1 Karate Coach", "More than 15 years of coaching experience"].map((item)=><li key={item} className="flex gap-3 rounded-lg border border-white/10 bg-black/30 p-3 text-sm font-semibold text-stone-200"><span className="text-red-400" aria-hidden="true">◆</span><span>{item}</span></li>)}</ul><p className="mt-5 text-sm leading-6 text-stone-500">No international refereeing licence is claimed on this page.</p></div></div></div></section>

    <section id="curriculum" className="border-y border-white/10 bg-black py-20 sm:py-24"><div className="section-shell"><div className="max-w-4xl"><p className="text-xs font-black uppercase tracking-[0.26em] text-red-300">Education framework</p><h2 className="hero-title mt-3 text-3xl font-bold text-white sm:text-5xl">Karate Refereeing Curriculum</h2><p className="mt-5 text-lg leading-8 text-stone-400">These modules establish the learning structure. Detailed explanations, signals, diagrams, and examples will be published only after they are checked against the applicable source documents.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-2">{modules.map(([number,title,topics])=><article key={title} className="rounded-2xl border border-white/10 bg-stone-950 p-6"><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-full border border-red-400/35 bg-red-950/30 font-black text-red-200">{number}</span><h3 className="hero-title text-2xl font-bold text-white">{title}</h3></div><ul className="mt-6 grid gap-x-5 gap-y-2 sm:grid-cols-2">{topics.map((topic)=><li key={topic} className="flex gap-2 text-sm leading-6 text-stone-400"><span className="text-red-400" aria-hidden="true">—</span><span>{topic}</span></li>)}</ul><p className="mt-6 border-t border-white/10 pt-4 text-xs font-black uppercase tracking-[0.13em] text-stone-600">Verified lesson content in development</p></article>)}</div></div></section>

    <section className="bg-stone-950 py-20 sm:py-24"><div className="section-shell"><div className="max-w-4xl"><p className="text-xs font-black uppercase tracking-[0.26em] text-red-300">Official and educational documents</p><h2 className="hero-title mt-3 text-3xl font-bold text-white sm:text-5xl">Refereeing Learning Library</h2><p className="mt-5 text-lg leading-8 text-stone-400">Search the supplied documents by category, topic, keyword, or extracted PDF text. Every record displays its issuing organization and version information.</p></div><div className="mt-10"><KnowledgeResourceLibrary resources={resources} articles={articles} compact /></div></div></section>

    <section className="border-y border-white/10 bg-black py-20"><div className="section-shell"><div className="max-w-4xl"><p className="text-xs font-black uppercase tracking-[0.26em] text-red-300">Prepared questions</p><h2 className="hero-title mt-3 text-3xl font-bold text-white sm:text-5xl">Karate Refereeing FAQ</h2><p className="mt-5 text-lg leading-8 text-stone-400">Answers remain unpublished until they are reviewed against the applicable current rule documents.</p></div><div className="mt-8 grid gap-3 lg:grid-cols-2">{faqs.map((question)=><details key={question} className="group rounded-xl border border-white/10 bg-stone-950 p-5"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between gap-4 font-bold text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-red-400">{question}<span className="text-red-300 transition group-open:rotate-45" aria-hidden="true">+</span></summary><p className="mt-4 border-t border-white/10 pt-4 leading-7 text-stone-400">A reviewed answer will be published after this topic is checked against the applicable rule document and edition.</p></details>)}</div></div></section>

    <section className="bg-red-950/20 py-16"><div className="section-shell"><div className="rounded-2xl border border-red-400/25 bg-black/55 p-6 sm:p-8"><h2 className="text-xl font-black text-white">Rules update notice</h2><p className="mt-3 max-w-4xl leading-7 text-stone-300"><strong>Competition rules and procedures may be updated by the relevant governing organizations. Visitors should always confirm that they are consulting the latest applicable official rules.</strong></p><p className="mt-4 max-w-4xl text-sm leading-6 text-stone-500">Third-party documents remain attributed to their issuing organizations. Coach-created educational content will be identified separately as original educational material from SHOTOKAN Karate Regina.</p></div></div></section>
  </main><Footer /></>;
}
