import { after } from "next/server";
import { accountFromRequest } from "@/lib/portal/auth";
import { sendPaymentSubmittedEmail } from "@/lib/portal/email";
import { assertCsrf, cleanText } from "@/lib/portal/security";
import { audit, mutatePortalDatabase, newId } from "@/lib/portal/store";
import { apiError, validationResponse } from "@/lib/portal/validation";

const allowedTypes = new Set(["image/jpeg", "image/png", "application/pdf"]);
export async function POST(request: Request) {
  try { assertCsrf(request); } catch { return apiError("Your secure form session expired. Refresh and try again.", 403, "CSRF_FAILED"); }
  const account = await accountFromRequest(request, { verified: true }); if (!account) return apiError("Please log in again.", 401, "AUTH_REQUIRED");
  const form = await request.formData().catch(() => null); if (!form) return apiError("The payment form could not be read.");
  const reference=cleanText(form.get("registrationReference"),40).toUpperCase(), transactionReference=cleanText(form.get("transactionReference"),120);const receipt=form.get("receipt");const errors:Record<string,string>={};if(!reference)errors.registrationReference="The registration reference is missing.";if(!transactionReference)errors.transactionReference="Please enter the transaction reference from your PayPal receipt.";
  let receiptData:{fileName:string;contentType:string;size:number;dataBase64:string}|null=null;
  if(receipt instanceof File&&receipt.size>0){if(receipt.size>2*1024*1024)errors.receipt="Receipt files must be 2 MB or smaller.";else if(!allowedTypes.has(receipt.type))errors.receipt="Upload a JPG, PNG, or PDF receipt.";else receiptData={fileName:receipt.name.slice(0,180),contentType:receipt.type,size:receipt.size,dataBase64:Buffer.from(await receipt.arrayBuffer()).toString("base64")};}
  if(Object.keys(errors).length)return validationResponse(errors);
  try{const saved=await mutatePortalDatabase((database)=>{const enrollment=database.enrollments.find((item)=>item.registrationReference===reference&&item.accountId===account.id);if(!enrollment)throw new Error("ENROLLMENT_NOT_FOUND");if(enrollment.paymentStatus==="Confirmed")throw new Error("ALREADY_CONFIRMED");if(database.payments.some((item)=>item.enrollmentId===enrollment.id&&item.status==="Pending Verification"))throw new Error("ALREADY_SUBMITTED");const student=database.students.find((item)=>item.id===enrollment.studentId);if(!student)throw new Error("STUDENT_NOT_FOUND");let receiptId:null|string=null;if(receiptData){receiptId=newId("receipt");database.receipts.push({id:receiptId,accountId:account.id,...receiptData,createdAt:new Date().toISOString()});}const now=new Date().toISOString();const payment={id:newId("payment"),enrollmentId:enrollment.id,accountId:account.id,amountCents:enrollment.tuitionCents,transactionReference,receiptId,status:"Pending Verification" as const,submittedAt:now,verifiedAt:null,verifiedByAccountId:null};database.payments.push(payment);enrollment.paymentStatus="Pending Verification";enrollment.enrollmentStatus="Payment Submitted";enrollment.updatedAt=now;audit(database,request,account.id,"payment.submitted","payment",payment.id,reference);return{enrollment,student,payment};});const base=process.env.NEXT_PUBLIC_SITE_URL||new URL(request.url).origin;after(()=>sendPaymentSubmittedEmail(account,saved.student,saved.enrollment,saved.payment,saved.payment.receiptId?`${base}/api/receipts/${saved.payment.receiptId}`:null).then(()=>undefined));return Response.json({success:true,message:"Your payment information was submitted and is pending administrator verification.",nextUrl:"/account/dashboard"});}catch(error){const reason=error instanceof Error?error.message:"";if(reason==="ENROLLMENT_NOT_FOUND")return apiError("The payment page could not be loaded for this registration reference.",404,reason);if(reason==="ALREADY_CONFIRMED")return apiError("This payment has already been confirmed.",409,reason);if(reason==="ALREADY_SUBMITTED")return apiError("Payment information has already been submitted and is pending verification.",409,reason);const ref=`PAYMENT-ERROR-${crypto.randomUUID().slice(0,6).toUpperCase()}`;console.error(ref,error);return apiError(`Payment information could not be saved. Error reference: ${ref}.`,500,"SERVER_ERROR");}
}
